services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "clave_segura"
      - key: N8N_HOST
        value: "https://n8n.onrender.com"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8n.onrender.com"
      - key: NHOST_GRAPHQL_URL
        value: "https://backend.nhost.app/v1/graphql"
      - key: NHOST_ADMIN_SECRET
        value: "tu_clave_secreta"
      - key: N8N_ENABLE_EXTERNAL_MODULES
        value: "true"
